using System.Collections.Generic;
using System.IO;
using Unity.Plastic.Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;

namespace Editor
{
    public class JsonClassGeneratorWindow : EditorWindow
    {
        private string jsonFolder = "Assets/StreamingAssets";
        private string outPutFolder = "Assets/Scripts/Config/AutoGenerated";

        [MenuItem("Tools/Json -> C# 自动生成器")]
        public static void ShowWindow()
        {
            GetWindow<JsonClassGeneratorWindow>("Json -> C# 自动生成器");
        }

        private void OnGUI()
        {
            GUILayout.Label("json配置表自动生成C#类", EditorStyles.boldLabel);
            jsonFolder = EditorGUILayout.TextField("Json文件夹路径", jsonFolder);
            outPutFolder = EditorGUILayout.TextField("输出C#类文件夹路径", outPutFolder);
            if(GUILayout.Button("生成所有Json对应的C#类"))
            {
                GenerateAll();
            }
        }

        private void GenerateAll()
        {
            if (!Directory.Exists(jsonFolder))
            {
                Debug.LogError("Json文件夹路径不存在: " + jsonFolder);
                return;
            }
            
            if (!Directory.Exists(outPutFolder))
            {
                Directory.CreateDirectory(outPutFolder);
            }
            
            var jsonFiles = Directory.GetFiles(jsonFolder, "*.json");
            List<string> classNames = new List<string>();
            foreach (var jsonFile in jsonFiles)
            {
                var fileName = Path.GetFileNameWithoutExtension(jsonFile);
                var className = char.ToUpper(fileName[0]) + fileName.Substring(1) + "Data";
                GenerateSingleClass(jsonFile, outPutFolder, className);
                classNames.Add(className);
            }
            
            GenerateConfigManager(outPutFolder, classNames);
            AssetDatabase.Refresh();
            Debug.Log("所有Json对应的C#类生成完成！");
        }

        private void GenerateSingleClass(string jsonFile, string outPutFolder, string className)
        {
            var json = File.ReadAllText(jsonFile);
            var arr = JArray.Parse(json);
            if (arr.Count == 0)
            {
                Debug.LogWarning($"Json数组为空: {jsonFile}");
                return;
            }
            
            JObject first = (JObject)arr[0];
            List<string> fields = new List<string>();
            foreach (var kv in first)
            {
                var type = GetCSharpType(kv.Value);
                fields.Add($"   public {type} {kv.Key};");
            }
            
            string classCode = 
                $@"using System;
               
[Serializable]
public class {className}
{{
{string.Join("\n", fields)}
}}
";
            
            File.WriteAllText(Path.Combine(outPutFolder, className + ".cs"), classCode);
            Debug.Log($"生成成功： {className}");
        }
        
        private string GetCSharpType(JToken token)
        {
            switch (token.Type)
            {
                case JTokenType.Integer:
                    return "int";
                case JTokenType.Float:
                    return "float";
                case JTokenType.String:
                    return "string";
                case JTokenType.Boolean:
                    return "bool";
                case JTokenType.Array:
                    return "List<" + GetCSharpType(token[0]) + ">";
                case JTokenType.Object:
                    return "object"; // 复杂对象可以进一步处理
                default:
                    return "object";
            }
        }

        private void GenerateConfigManager(string outPutFolder, List<string> classNames)
        {
            var fields = new List<string>();
            var dicts = new List<string>();
            var loads = new List<string>();
            foreach (var className in classNames)
            {
                var fileName = className.Replace("Data", "") + ".json";
                fields.Add($"    public static List<{className}> {className}List;");
                dicts.Add($"    public static Dictionary<int, {className}> {className}Dict;");
                loads.Add($@"
        {className}List = ConfigLoader.LoadList<{className}>(""{fileName}"");
        {className}Dict = {className}List.ToDictionary(item => item.id);");
            }

            string code = 
$@"using System.Collections.Generic;
using System.Linq;
public static class ConfigManager
{{
{string.Join("\n", fields)}

{string.Join("\n", dicts)}

    public static void Load()
    {{{string.Join("\n", loads)}
    }}
}}
";
            
            File.WriteAllText(Path.Combine(outPutFolder, "ConfigManager.cs"), code);
            Debug.Log("生成成功： ConfigManager.cs");
        }
    }
}